# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sharon Knieper
email: sharonknieper@gmail.com
description:  Brooklyn based UX and Drupal expertise for hire. Argentine Tango and Feldenkrais aficionado.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sharonknieper.com" # the base hostname & protocol for your site, e.g. http://example.com

texture:
  title: Sharon Knieper
  #description: >- # this means to ignore newlines until "baseurl:"
  tagline: Brooklyn based UX, Information Architecture and Drupal expertise for hire. <br> Argentine Tango and Feldenkrais aficionado.
  date_format: "%b %-d, %Y"
  social_links:
    twitter: sknieper
    github:  knieper
    linkedIn: in/sharon-knieper-a573734 # format: locale/username
  #analytics_id: '< YOUR ID >'
  #showNav: true
  #show_excerpts: true
  #style: [black]
  style: 'SRK' #my custom style, prints as 'texture-SRK' class

collections:
  - work

# Build settings
markdown: kramdown
#theme: minima
theme: texture
remote_theme: thelehhman/texture
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
